### ISSUE TITLE
Should I exclude the low quality bases and adapter sequences from fastq files?

### ISSUE THREAD

**Issue by Apprentice2** [icbi-lab/NeoFuse#10]
I am trying to apply fastq files of RNA-seq (paired-end) to NeoFuse to identify neoantigens.
My fastq files may contain low quality bases and adapter sequences. Should I prepare fastq files that excluded the low quality bases and adapter sequences and apply them to NeoFuse?

I would appreciate it if you could tell me.

**Comment by abyssum** [comment]
Hello,

There is no definitive answer to your question. STAR addresses both issues with soft-clipping, but for example, if you have known issues of read-through adapter contamination you can consider trimming the reads before running NeoFuse. You should always keep in mind that there's a trade-off between precision and sensitivity for uniquely mapped reads and while aggressive trimming might increase the precision of unique mappers, it might also affect the portion of split reads and discordant mates.

If for any reason you decide to trim first, I would suggest running 1-2 samples with and without trimming to check which result can better explain your data (for example, if there are recurrent known fusion genes for the condition/disease in the results of one of the two approaches).

**Comment by Apprentice2** [comment]
Thank you for your prompt reply. It was very helpful.
