### ISSUE TITLE
Error with NeoFuse execution

### ISSUE THREAD

**Issue by Prathyusha-konda** [icbi-lab/NeoFuse#17]
Hi, I am trying to execute neofuse with the following command and I am getting error about unable to create folder in a non-existent path (/mnt/out - I am not sure why it's trying to write here, this path does not exist - I'm running on a cluster). Can you please help me with this? Thank you very much.

Command:
NeoFuse -o ./NeoFuse_data/output/  \
        -1 ./p2/a2/celllinedata/B10/B10_1.fq  \
        -2 ./p2/a2/celllinedata/B10/B10_2.fq  \
        -s ./Reference/STARindex/  \
        -g ./Reference/GRCh38.primary_assembly.genome.fa  \ 
        -a ./Reference/gencode.v31.annotation.gtf  \ 
        -M 11   --docker

Error:
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
mkdir: cannot create directory '/mnt/out/output/B10_1.fq': Permission denied
[-------------------------------- [NeoFuse] --------------------------------]

[18:21:45]  Paired End (PE) Reads detected: commencing processing
[18:21:45]  Processing files B10_1.fq - B10_2.fq
[18:21:45]  STAR Run started
/usr/local/bin/NeoFuse_single: line 224: /mnt/out/output/B10_1.fq/LOGS/B10_1.fq.STAR.err: No such file or directory
/usr/local/bin/NeoFuse_single: line 234: /mnt/out/output/B10_1.fq/LOGS/B10_1.fq.samtools.log: No such file or directory
[18:21:45]  Arriba Run started
/usr/local/bin/NeoFuse_single: line 250: /mnt/out/output/B10_1.fq/LOGS/B10_1.fq.arriba.log: No such file or directory

EXITING because of FATAL ERROR: could not create output file: /mnt/out/output/B10_1.fq/Arriba/B10_1.fq.Log.out
Check if the path /mnt/out/output/B10_1.fq/Arriba/B10_1.fq. exists and you have permissions to write there

Aug 09 18:21:45 ...... FATAL ERROR, exiting
An error occured during STAR/Arriba run, check the log files in /home/pk576/NeoFuse_data/output/B10_1.fq/LOGS/ for more details

**Comment by abyssum** [comment]
Hello @Prathyusha-konda,

The `/mnt/out` NeoFuse is trying to access is the actual mount point to `/home/pk576/NeoFuse_data/output/`. So this should not cause any problems. 
You are getting a `Permission denied` tho, which means that the container does not have permission to write on this specific path. I don't know what's the configuration on your cluster but Docker containers run as super user (sudo), also keep in mind that the container environment runs as user: `NeoFuse` (there's a reason for that).

I am afraid there's not much we can do from our side atm (but I will try to figure out a workaround), what I can suggest for now is to:
1. Report the issue to your sys admin.
2. Check if there's a singularity installation on your HPC and run NeoFuse with the `--singularity` flag.

**Comment by Prathyusha-konda** [comment]
Hi @abyssum,

Thank you so much for responding so quickly, really appreciate it. This is my first time using docker so I was not sure what that error meant - I'll ask the bioinformatics core if they can enable permissions :)

I don't think we have singularity, unfortunately.
