### ISSUE TITLE
asking about the pattern of HLA.txt file for running multiple sample  

### ISSUE THREAD

**Issue by Tanyaluckk** [icbi-lab/NeoFuse#20]
Hi, 
I would like to customize the HLA input, which can be added with the optional argument -C.
I wonder about the pattern of the HLA.txt file that I should prepare for running multiple samples.
May I ask how to prepare it?

Thank you in advance.

Tanyaluck

**Comment by abyssum** [comment]
Hello @Tanyaluckk,

First of all, thank you for using NeoFuse.

Unfortunately, we are dropping the support for custom HLA lists for multiple samples. The reasoning being that this way the processes would not be able to run in parallel on HPC or AWS infrastructures, heavily impacting the computational efficiency of the tool. We are currently migrating NeoFuse to Nextflow's DSL2 and in a few months we will release a new version - supporting MHC class II neoantigens as well (the current version of NeoFuse will become obsolete with the new release).

Thank you for pointing this out, I will update the README.md with the relevant information and also include an example of the format for the custom HLA list txt file in the next few days.

In the meantime, if you would like to run NeoFuse for single samples, the custom HLA list should be a simple txt file (one for each patient) where each row represents a different HLA type in 4 digit resolution. Here is an example:

```
A*01:01
A*24:02
B*08:01
B*35:02
C*04:01
C*07:01
```

I hope this helps.

**Comment by Tanyaluckk** [comment]
Thank you so much for your quick reply!
