### ISSUE TITLE
Adding Arriba "-k" and "-f" options to NeoFuse command line option list

### ISSUE THREAD

**Issue by fdkuo** [icbi-lab/NeoFuse#6]
In some cases, Arriba discarded known frequent fusions without giving clear clue about the reason for discarding. It will be very helpful if its "-k" option can be included in the NeoFuse command line so the fusion can be included for the rest of the pipeline. If not a burden, could you please also add the "-f" option as well so one can test and build a set of optimized Arriba filters for reporting fusions. Many thanks!

David

**Comment by abyssum** [comment]
Hello David,

Thank you for your input, I will try to make a hotfix as soon as possible!

Best,
Georgios

**Comment by abyssum** [comment]
Hello David,

I have implemented the features in the latest release of NeoFuse (v1.1.2). Please be aware:
- You need to clone the latest release and re-build the NeoFuse image.
- The flag for the known/recurrent fusions file is "-K" (not "-k" as in the Arriba command line options)
- "-f" will only accept comma-separated lists (in the form: "uninteresting_contigs,non_coding_neighbors", etc.) as space-separated lists will break the getopt() functionality (will be addressed in future releases).

I have run some tests and didn't get any errors until now, please let me know if this works for you as well.

(I am closing this issue, feel free to re-open or create a new one if any errors occur)

Best,
Georgios
