### ISSUE TITLE
Does the result change between single samples and multiple samples?

### ISSUE THREAD

**Issue by Apprentice2** [icbi-lab/NeoFuse#9]
I am trying to implement NeoFuse using a supercomputer. I know that NeoFuse has single samples mode and multiple samples mode. I want to apply NeoFuse to RNA-seq data of 20 samples, but when I run it in multiple samples mode, it fails with a permission error. So, I want to apply NeoFuse to each of the 20 samples in the single sample mode. So I would like to ask, is there any difference in the results between single sample mode and multiple sample mode?
I would appreciate it if you could tell me.

**Comment by riederd** [comment]
There should be no difference. In single mode only one sample per run is processed and in multi sample mode multiple samples are in a run. HTH

**Comment by Apprentice2** [comment]
Thank you very match!
